Add option for modal size
markwalet/nova-modal-response pull request #5
Opened 2023-12-21 06:45 UTC by Kaylakaze

Having the modal locked to 2xl is very inconvenient when it only takes a tiny change to make it selectable.

2023-12-21 09:36 UTC, markwalet commented on README.md
> +
Can you remove this line again?

2023-12-21 09:38 UTC, markwalet commented
Thanks for your contribution. I appreciate that you kept the 2xl size there as a default to prevent breaking changes!

This was very much a tiny package to scratch my own itch. So I'm glas someone else is helping with improving on it. Once you've updated the readme again I'll merge it and tag a new version.

2023-12-21 11:49 UTC, markwalet requested changes
Besides the changelog thing, can you minify the asset again?

2023-12-23 16:59 UTC, Kaylakaze commented
I'm primarily a backend developer and haven't really used Vue in quite a
few years, so I'm not really sure how to minify the asset these days. I was
mostly providing the PR so you could see the small change. If you want to
throw out my PR, add the change yourself and pack it, I have no objections.

On Thu, Dec 21, 2023 at 6:50 AM Mark Walet ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Besides the changelog thing, can you minify the asset again?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/markwalet/nova-modal-response/pull/5#pullrequestreview-1792810520>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKM5B2VISTCKVGNSVMYNSDYKQO6ZAVCNFSM6AAAAABA55LWECVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOJSHAYTANJSGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-12-23 17:48 UTC, markwalet commented
No problem, i want to give you credit to the contribution by  merging this ofcourse. But I can do it myself as well.

I think `npm run prod` should cover the minification. If it doesn't work I can do it myself after Christmas :+1:

2024-01-23 15:34 UTC, markwalet commented
Are you able to adjust the PR yourself? I'd love to pull in your PR directly so you get accredited for your work. But I can do it myself if you don't have the time right now.

2024-01-31 08:05 UTC, markwalet commented
Closing this PR because of inactivity. Feature is added in V0.2.1

2024-01-31 08:05 UTC, closed without merging